name: Build

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: openwrtorg/sdk:ramips-mt76x8-21.02.0
    defaults:
      run:
        working-directory: /home/build/openwrt
    steps:
      - name: Add feeds
        run: echo "src-git airsaned https://github.com/ypopovych/AirSane-openwrt.git^${GITHUB_SHA}" >> feeds.conf.default
      - name: Update feeds
        run: ./scripts/feeds update base packages airsaned
      - name: Make defconfig
        run: make defconfig
      - name: Install feeds
        run: ./scripts/feeds install airsaned
      - name: Compile
        run: make package/airsaned/compile -j$(nproc)
      - name: Get version
        run: |
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" airsaned/Makefile`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" airsaned/Makefile`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "::set-env name=PKG_VERSION::$PKG_VERSION"
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: airsaned-mipsel24kc-${{ env.PKG_VERSION }}.ipk
          path: bin/packages/mipsel_24kc/airsaned/airsaned-${{ env.PKG_VESION }}.ipk
