name: Build

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:ramips-mt76x8-21.02.0
      options: --user root
    defaults:
      run:
        working-directory: /home/build/openwrt
    steps:
      - name: Check env
        run: |
          export
          ls -la $GITHUB_ENV
          echo "TEST=TST" >> $GITHUB_ENV
      - name: Add feeds
        run: echo "src-git airsaned https://github.com/ypopovych/AirSane-openwrt.git^${GITHUB_SHA}" >> feeds.conf.default
      - name: Update feeds
        run: ./scripts/feeds update base packages airsaned
      - name: Make defconfig
        run: make defconfig
      - name: Install feeds
        run: ./scripts/feeds install airsaned
      - name: Compile
        run: make package/airsaned/compile -j$(nproc)
      - name: Get version
        run: |
          export MAKEFILE="./feeds/airsaned/airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_mipsel_24kc.ipk
          path: bin/packages/mipsel_24kc/airsaned/airsaned_${{ env.PKG_FULL_VERSION }}_mipsel_24kc.ipk
